
[@ui.bambooSection titleKey="section.asoc"]
	[@ww.select labelKey="label.cred" name="selectedCred" required="true" list="credList"/]
	[@ww.textfield labelKey="label.appid" name="appId" required="true"/]
	[@ww.select labelKey="label.scan.type" name="selectedScanType" required="true" list="scanType"/]
	[@ui.bambooSection dependsOn="selectedScanType" showOn="DynamicAnalyzer"]
		[@ww.textfield labelKey="label.target" name="target" required="true"/]
		[@ww.checkbox labelKey="label.additional.options" name="additionalOptions" toggle="true"/]
		[@ui.bambooSection titleKey="section.additional.opts" descriptionKey="section.additional.opts.desc" dependsOn="additionalOptions" showOn="true"]
        	[@ww.select labelKey="dyn.label.scan.type.option" name="selScanOption" list="scanOptionList"/]
        	[@ww.select labelKey="dyn.label.test.optimization" name="selTestOptimization" list="testOptimizationList"/]
        	[@ww.textfield labelKey="dyn.label.login.user" name="loginUser"/]
        	[@ww.textfield labelKey="dyn.label.login.password" name="loginPassword"/]
        	[@ww.textfield labelKey="dyn.label.third.credential" name="thirdCredential"/]
        	[@ww.select labelKey="dyn.label.presence" name="selPresence" list="presenceList"/]
        	[@ww.textfield labelKey="dyn.label.scan.file" name="scanFile"/]
        [/@ui.bambooSection]
	[/@ui.bambooSection]
	[@ui.bambooSection dependsOn="selectedScanType" showOn="StaticAnalyzer"]
		[@ww.checkbox labelKey="label.additional.options" name="additionalOptions" toggle="true"/]
		[@ui.bambooSection titleKey="section.additional.opts" descriptionKey="section.additional.opts.desc" dependsOn="additionalOptions" showOn="true"]
			[@ww.textfield labelKey="label.custom.target" name="target"/]
			[@ww.checkbox labelKey="label.open.source.only" name="openSourceOnly" toggle="true"/]
		[/@ui.bambooSection]
	[/@ui.bambooSection]
	[@ww.checkbox labelKey="label.suspend" name="suspendJob" toggle="true"/]
[/@ui.bambooSection]

[@ui.bambooSection titleKey="section.fail" descriptionKey="section.fail.desc" dependsOn="suspendJob" showOn="true"]
	[@ww.textfield labelKey="label.high" name="maxHigh"/]
	[@ww.textfield labelKey="label.medium" name="maxMedium"/]
	[@ww.textfield labelKey="label.low" name="maxLow"/]
[/@ui.bambooSection]
