
[@ui.bambooSection titleKey="section.asoc"]
	[@ww.label labelKey="label.cred" name="selectedCred"/]
	[@ww.label labelKey="label.appid" name="appId"/]
	[@ww.label labelKey="label.scan.type" name="selectedScanType"/]
	[@ui.bambooSection dependsOn="selectedScanType" showOn="DynamicAnalyzer"]
		[@ww.label labelKey="label.target" name="target"/]
		[@ww.checkbox labelKey="label.additional.options" name="additionalOptions" toggle="true" disabled="true"/]
		[@ui.bambooSection titleKey="section.additional.opts" descriptionKey="section.additional.opts.desc" dependsOn="additionalOptions" showOn="true"]
			[@ww.label labelKey="dyn.label.scan.type.option" name="selScanOption"/]
			[@ww.label labelKey="dyn.label.test.optimization" name="selTestOptimization"/]
			[@ww.label labelKey="dyn.label.login.user" name="loginUser"/]
			[@ww.label labelKey="dyn.label.login.password" name="loginPassword"/]
			[@ww.label labelKey="dyn.label.third.credential" name="thirdCredential"/]
			[@ww.label labelKey="dyn.label.presence" name="selPresence"/]
			[@ww.label labelKey="dyn.label.scan.file" name="scanFile"/]
		[/@ui.bambooSection]
	[/@ui.bambooSection]
	[@ui.bambooSection dependsOn="selectedScanType" showOn="StaticAnalyzer"]
		[@ww.checkbox labelKey="label.additional.options" name="additionalOptions" toggle="true" disabled="true"/]
		[@ui.bambooSection titleKey="section.additional.opts" descriptionKey="section.additional.opts.desc" dependsOn="additionalOptions" showOn="true"]
			[@ww.label labelKey="label.custom.target" name="target"/]
			[@ww.checkbox labelKey="label.open.source.only" name="openSourceOnly" toggle="true" disabled="true"/]
		[/@ui.bambooSection]
    [/@ui.bambooSection]
	[@ww.checkbox labelKey="label.suspend" name="suspendJob" toggle="true" disabled="true"/]
[/@ui.bambooSection]

[@ui.bambooSection titleKey="section.fail" dependsOn="suspendJob" showOn="true"]
	[@ww.label labelKey="label.high" name="maxHigh"/]
	[@ww.label labelKey="label.medium" name="maxMedium"/]
	[@ww.label labelKey="label.low" name="maxLow"/]
[/@ui.bambooSection]
